	INSERT INTO ingrediente_alergenico (id, nome) VALUES (1, 'Leite');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (2, 'Ovo');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (3, 'Frutos do Mar');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (4, 'Peixe');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (5, 'Soja');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (6, 'Trigo');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (7, 'Centeio');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (8, 'Cevada');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (9, 'Aveia');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (10, 'Amendoim');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (11, 'Amendoa');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (12, 'Avelã');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (13, 'Castanha');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (14, 'Macadâmia');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (15, 'Pistache');
    INSERT INTO ingrediente_alergenico (id, nome) VALUES (16, 'Nozes');
    
	INSERT INTO restricao (id, nome) VALUES (1, 'Sem Glúten');
    INSERT INTO restricao (id, nome) VALUES (2, 'Sem Lactose');
    INSERT INTO restricao (id, nome) VALUES (3, 'Sem Açúcar');
    INSERT INTO restricao (id, nome) VALUES (4, 'Sem Sódio');
    INSERT INTO restricao (id, nome) VALUES (5, 'Sem Gordura');
    INSERT INTO restricao (id, nome) VALUES (6, 'Vegetariano');
    INSERT INTO restricao (id, nome) VALUES (7, 'Vegano');
    INSERT INTO restricao (id, nome) VALUES (8, 'Cetogênico');
    INSERT INTO restricao (id, nome) VALUES (9, 'Low Carb');